# -*- coding: utf-8 -*-
"""First order Initial Value Problem with Euler's Method.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ETxCjbAxpoB5-vCFIUuCtp6uzQC2_AJ5
"""

def euler_method(f, x0, y0, h, num_steps):

    solution = [(x0, y0)]
    x = x0
    y = y0

    for _ in range(num_steps):
        y += h * f(x, y)   # Euler's method formula
        x += h
        solution.append((x, y))

    return solution


# Example usage
def example_function(x, y):
    return x * y  # Function representing dy/dx


# Get user input
x0 = float(input("Enter the initial value of x: "))
y0 = float(input("Enter the initial value of y: "))
h = float(input("Enter the step size (h): "))
num_steps = int(input("Enter the number of steps: "))

# Solve the IVP using Euler's method
solution = euler_method(example_function, x0, y0, h, num_steps)

# Print the solution
print("\nApproximate Solution using Euler's method:")
for point in solution:
    print(f"x = {point[0]}, y = {point[1]}")